$kind: http-request
name: Update
url: "{{base_url}}/tasks/{{taskId}}"
method: PUT
body:
  type: json
  content: "{\r

    \    \"title\": \"Погодувати кота\",\r

    \    \"description\": \"Купити\",\r

    \    \"deadline\": 1778000400\r

    }"
order: 1851934327446289
